### ISSUE TITLE
files missing

### ISSUE THREAD

**Issue by Prajwal7700** [Vibhuarvind/Depression-Detect#1]
# Hi the text emotion recognition  and text preprocessor are absent in library folder.

**Comment by Vibhuarvind** [comment]
> # Hi the text emotion recognition and text preprocessor are absent in library folder.

This project was recently completed for audio and video functions; but, because the work is still ongoing, I have not completed it for textual emotion recognition. Remove the text emotion libraries from main.py if you want to use it.

**Comment by Prajwal7700** [comment]
Ok thanks.
Can you guide us how to work with it because we are also working on similar
project.
